version: 2
jobs:
  build:
    docker:
      # See docker/Dockerfile
      - image: feedreader/fedora-feedreader-devel
    working_directory: ~/FeedReader
    steps:
      - checkout
      - run: dnf install meson ninja-build libappstream-glib-devel
      - run: meson builddir
      - run: ninja -C builddir
