version: 2
jobs:
  build:
    docker:
      # See docker/Dockerfile
      - image: feedreader/fedora-feedreader-devel
    working_directory: ~/FeedReader
    steps:
      - checkout
      - run: cmake .
      - run: make
