PACKAGE=FeedReader
VERSION=2.0-dev
JSON=org.gnome.FeedReader.json
ARCH=x86_64
BRANCH=master
GIT=master
BUILD=$(GIT)-` date +"%Y%m%d" `
BUNDLE=$(PACKAGE)-$(VERSION)-$(BUILD).$(ARCH)
RELEASE_GPG_KEY=09624E3452B19227EE2CD0107E74B9AF91B7D5D5
KEY_USER=scurtu@mail.de
# The url of your public repository which is embedded in the generated
# .flatpakref file
URL=http://feedreader.xarbit.net.s3-website.eu-central-1.amazonaws.com/feedreader-repo

