PACKAGE=FeedReader
VERSION=2.0.2
JSON=org.gnome.FeedReader.json
ARCH=x86_64
BRANCH=stable
GIT=stable
RUNTIME_VERSION=3.24
BUILD=$(GIT)-` date +"%Y%m%d" `
BUNDLE=$(PACKAGE)-$(VERSION)-$(BUILD).$(ARCH)
RELEASE_GPG_KEY=09624E3452B19227EE2CD0107E74B9AF91B7D5D5
KEY_USER=scurtu@mail.de
# user + host : user@ip
SSH_USER=jscurtu@192.168.10.10
# Path to repo
RSYNC_PATH=/volume1/Shares/S3/feedreader/
# The url of your public repository which is embedded in the generated
# .flatpakref file
URL=http://feedreader.xarbit.net/feedreader-repo

