FROM fedora:latest

RUN dnf -y install \
        cmake \
        gcc \
        gettext \
        git \
        gnome-online-accounts-devel \
        gstreamer1-devel \
        gstreamer1-plugins-base-devel \
        gtk3-devel \
        json-glib-devel \
        libcurl-devel \
        libgee-devel \
        libnotify-devel \
        libpeas-devel \
        libsecret-devel \
        libsoup-devel \
        libxml2-devel \
        rest-devel \
        sqlite-devel \
        vala \
        webkitgtk4-devel
