
  name: feedreader
  version: 2.2+dev # just for humans, typically '1.2+git' or '1.3.2'
  summary: Modern desktop app designed to complement web-based RSS accounts. 
  description: |
    FeedReader is a modern desktop application designed to complement existing
    web-based RSS accounts. It combines all the advantages of web based services
    like synchronisation across all your devices with everything you expect from
    a modern desktop application.

  grade: stable
  confinement: strict
  
  apps:
    feedreader:
     command: feedreader
     plugs: [network, home]
     # add .desktop file
     
  parts:
    feedreader:
      plugin: cmake
      source: https://github.com/jangernert/FeedReader.git
      source-type: git
      source-subdir: .
      build: |
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
      snap:
        - lib/*
        - usr/bin/*
        - usr/lib/*
        - usr/share/*
      build-packages:
         - build-essential
         - cmake
         - pkg-config 
         - libgirepository1.0-dev 
         - libgtk-3-dev 
         - libsoup2.4-dev 
         - libjson-glib-dev 
         - libwebkit2gtk-4.0-dev 
         - libsqlite3-dev 
         - libsecret-1-dev 
         - libnotify-dev 
         - libxml2-dev 
         - librest-dev 
         - libgee-0.8-dev 
         - libgstreamer1.0-dev 
         - libgstreamer-plugins-base1.0-dev 
         - libgoa-1.0-dev 
         - libcurl4-gnutls-dev 
         - libpeas-dev    
    valac:
      plugin: autotools
      source: http://download.gnome.org/sources/vala/0.38/vala-0.38.8.tar.xz
      build-packages:
         - flex    
         - bison
         - build-essential
         - libglib2.0-dev
         - libgraphviz-dev
